<script src="../../assets/js/jquery.min.js"></script>
<script src="../../assets/js/bootstrap.bundle.min.js"></script>
<script src="../../assets/js/metisMenu.min.js"></script>
<script src="../../assets/js/simplebar.min.js"></script>
<script src="../../assets/js/waves.min.js"></script>
<script src="../../assets/js/feather.min.js"></script>
<script src="../../assets/js/pace.min.js"></script>
<script src="../../assets/js/choices.min.js"></script>
<script src="../../assets/js/app.js"></script>
<!-- <script src="../../assets/js/form-advanced.init.js"></script> -->
